[workspace]
resolver = "2"

members = [
    "os/kernel",
    "os/application/hello",
    "os/application/shell",
    "os/application/uptime",
    "os/application/date",
    "os/application/e1000"]

# [profile.release]
# debug = true